- name: Setup Java Boilerplate Application
  hosts: all
  become: yes
  become_flags: '-H'
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install essential packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - openjdk-17-jdk
        - maven
        - postgresql
        - postgresql-contrib
        - rabbitmq-server

    - name: Create hng user with sudo privileges
      user:
        name: hng
        groups: sudo
        append: yes
        create_home: yes
        home: /home/hng
        shell: /bin/bash

    - name: Grant hng user sudo without password
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^hng'
        line: 'hng ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

    - name: Create the /opt/stage_5b directory
      file:
        path: /opt/stage_5b
        state: directory
        owner: hng
        group: hng
        mode: '0755'
          
    - name: Add /opt/stage_5b to Git safe directories for hng
      become: false
      become_user: hng
      command: git config --global --add safe.directory /opt/stage_5b
    
    - name: Ensure the correct ownership of the directory before git operations
      file:
        path: /opt/stage_5b
        owner: hng
        group: hng
        recurse: yes

    - name: Clean repository if exists
      become: true
      command: sudo -u hng git reset --hard HEAD
      args:
        chdir: /opt/stage_5b
      ignore_errors: yes

    - name: Fetch latest changes from remote
      become: true
      command: sudo -u hng git fetch https://github.com/hngprojects/hng_boilerplate_java_web
      args:
        chdir: /opt/stage_5b

    - name: Resolve Maven dependencies
      shell: mvn dependency:resolve
      args:
        chdir: /opt/stage_5b
      become: false
      become_user: hng


    - name: Ensure PostgreSQL service is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create /var/secrets directory
      file:
        path: /var/secrets
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Save PostgreSQL credentials to /var/secrets/pg_pw.txt
      copy:
        content: |
          POSTGRES_USER=admin
          POSTGRES_PASSWORD=yourpassword
        dest: /var/secrets/pg_pw.txt
        owner: postgres
        group: postgres
        mode: '0600'

    - name: Set up PostgreSQL database
      become: false
      shell: |
        sudo -u postgres psql -c "CREATE DATABASE hng_db;"
        sudo -u postgres psql -c "CREATE USER admin WITH ENCRYPTED PASSWORD 'yourpassword';"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE hng_db TO admin;"

    - name: Set up Nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx as a reverse proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/stage_5b
      notify:
        - Restart Nginx

    - name: Enable Nginx site
      command: ln -s /etc/nginx/sites-available/stage_5b /etc/nginx/sites-enabled/
      args:
        removes: /etc/nginx/sites-enabled/stage_5b
      notify:
        - Restart Nginx

    - name: Build the application using Maven
      shell: |
        cd /opt/stage_5b
        ./mvnw clean install
      become_user: hng

    - name: Run the application
      shell: |
        cd /opt/stage_5b
        nohup java -jar target/your-app.jar > /var/log/stage_5b/out.log 2> /var/log/stage_5b/error.log &
      become_user: hng

    - name: Ensure /var/log/stage_5b exists
      file:
        path: /var/log/stage_5b
        state: directory
        owner: hng
        group: hng

    - name: Ensure logs are owned by hng
      file:
        path: /var/log/stage_5b
        recurse: yes
        owner: hng
        group: hng

    - name: Run application tests using Maven
      shell: |
        cd /opt/stage_5b
        ./mvnw test
      become_user: hng

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

