---
- name: Setup Java Boilerplate Application
  hosts: hng
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Create hng user with sudo privileges
      user:
        name: hng
        groups: sudo
        append: yes
        create_home: yes

    - name: Create /opt/stage_5b directory
      file:
        path: /opt/stage_5b
        state: directory
        owner: hng
        group: hng

    - name: Clone the repository into /opt/stage_5b
      git:
        repo: https://github.com/hngprojects/hng_boilerplate_java_web
        dest: /opt/stage_5b
        version: DevOps
        force: yes
      become_user: hng

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Save PostgreSQL credentials to /var/secrets/pg_pw.txt
      copy:
        content: |
          POSTGRES_USER=admin
          POSTGRES_PASSWORD=yourpassword
        dest: /var/secrets/pg_pw.txt
        owner: postgres
        group: postgres
        mode: '0600'

    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present

    - name: Install Java and other dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-17-jdk
        - maven
        - git
        - curl
        - zip
        - unzip
        - nginx

    - name: Set up Nginx
      apt:
        name: nginx
        state: present

    - name: Configure Nginx as a reverse proxy
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/stage_5b
      notify:
        - Restart Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/stage_5b
        dest: /etc/nginx/sites-enabled/
        state: link
      notify:
        - Restart Nginx

    - name: Ensure application starts on 127.0.0.1:3000
      shell: |
        cd /opt/stage_5b
        nohup mvn spring-boot:run > /var/log/stage_5b/out.log 2> /var/log/stage_5b/error.log &
      become_user: hng

    - name: Ensure /var/log/stage_5b exists
      file:
        path: /var/log/stage_5b
        state: directory
        owner: hng
        group: hng

    - name: Ensure logs are owned by hng
      file:
        path: /var/log/stage_5b
        recurse: yes
        owner: hng
        group: hng

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

